**Numpy Introduction and basic functions**

In [673]:
import numpy as np

In [674]:
a = np.array([1, 3, 5], dtype="int16")
b = np.array([[2.0, 6.5, 7.8], [2.0, 6.5, 7.8]])
print(a)
print(b)

[1 3 5]
[[2.  6.5 7.8]
 [2.  6.5 7.8]]


In [675]:
print(a.ndim)
print(b.ndim)

1
2


In [676]:
# Get shape
a.shape

(3,)

In [677]:
b.shape

(2, 3)

In [678]:
# Get type
a.dtype

dtype('int16')

In [679]:
# Get size (bytes) for each entry - for array a we have specified dtype = "int16",
#which reduces the size. Can be used if numbers are small
a.itemsize

2

In [680]:
# Get size (bytes)
b.itemsize

8

In [681]:
# Get size of array
a.size

3

In [682]:
# Get total size : a.itemsize * a.size
a.nbytes

6

**Accesing / Changing specific elements, rows, columns, etc.** 

In [683]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [684]:
c.shape

(2, 7)

In [685]:
# Get a specific element
c[1, 5]

13

In [686]:
# also possible using negative location: 
c[1, -2]

13

In [687]:
# Get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [688]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [689]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [690]:
# Change a number
c[1, 5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [691]:
# change an entire column
c[1, :] = 5
print(c)

[[1 2 3 4 5 6 7]
 [5 5 5 5 5 5 5]]


In [692]:
# change a row
c[:, 2] = 6
print(c)

[[1 2 6 4 5 6 7]
 [5 5 6 5 5 5 5]]


In [693]:
# change a row - different values
c[:, 3] = [7, 8]
print(c)

[[1 2 6 7 5 6 7]
 [5 5 6 8 5 5 5]]


In [694]:
# Change an entire row - specific values
c[1, :] = [9, 8, 7, 6, 5, 4, 3]
print(c)

[[1 2 6 7 5 6 7]
 [9 8 7 6 5 4 3]]


In [695]:
# Change - a little bit more fancy
c[:, 0:15:2] = 0
c[:, 1:15:2] = 1
print(c)

[[0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]]


In [696]:
# 3d example
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [697]:
d.shape

(2, 2, 2)

In [698]:
# Get a specific element. Let´s try to get 4 (work outside in)
d[0, 1, 1]

4

In [699]:
# Get the first matrix
d[0, :, :]

array([[1, 2],
       [3, 4]])

In [700]:
# Get the first rows of both 2d dimension matrices
d[:, 0, :]

array([[1, 2],
       [5, 6]])

In [701]:
# replace - first matrix all values = 1
d[0, :, :] = 1
print(d)

[[[1 1]
  [1 1]]

 [[5 6]
  [7 8]]]


In [702]:
# replace - second matrix with 2, 3, 4, 5, 
d[1, :, :] = [[2, 3], [4, 5]]
print(d)

[[[1 1]
  [1 1]]

 [[2 3]
  [4 5]]]


**Initializing different types of arrays**

In [703]:
# All 0´s arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [704]:
# 3D version of all 0´s
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [705]:
# All 1´s
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [706]:
# 3D Version all 1´s
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [707]:
# can also specify the size of the data type
np.ones((2, 7), dtype = "int32")

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [708]:
# create a matrix with specific values
np.full((3, 6), 57)

array([[57, 57, 57, 57, 57, 57],
       [57, 57, 57, 57, 57, 57],
       [57, 57, 57, 57, 57, 57]])

In [709]:
# create a matrix with the structure of an already created array (full_like) --> c array in our case
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [710]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.0999856 , 0.94094203, 0.16745869],
        [0.05472914, 0.32172364, 0.43728204]],

       [[0.82233233, 0.88968852, 0.03452975],
        [0.76817734, 0.06618812, 0.05969864]],

       [[0.67430687, 0.43217795, 0.34497225],
        [0.9658792 , 0.06298726, 0.50464404]],

       [[0.96224883, 0.77958227, 0.41533004],
        [0.43199348, 0.62171239, 0.72569291]]])

In [711]:
# random sample with shape of previous matrix --> c array
np.random.random_sample(c.shape)

array([[0.3896935 , 0.83212106, 0.56715511, 0.01559502, 0.27386602,
        0.84769917, 0.89839825],
       [0.75376133, 0.60003257, 0.21006463, 0.72403598, 0.78382987,
        0.90121519, 0.63503588]])

In [712]:
# random integer values from 0 to 10
np.random.randint(11, size=(3, 3, 3))

array([[[ 7,  3,  4],
        [ 7,  9,  6],
        [ 6,  1,  5]],

       [[ 0,  5,  8],
        [ 0,  9,  7],
        [ 6,  0,  6]],

       [[ 3,  3,  9],
        [ 3,  3,  0],
        [10,  8,  0]]])

In [713]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [714]:
# repeat arrays (must specify: array to be repeated, number of repetitions, axis for repetitions)
# The axis specifies the direction in which elements should be added. Axis 0 represents the columns.
arr = np.array([[1, 2, 3]])
e = np.repeat(arr,4, axis = 0)
print(e)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [715]:
# Exercise to build a specific 5x5 array
f = np.ones((5, 5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [716]:
f[1:4, 1:4:1] = 0
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [717]:
f[2, 2] = 9
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be carefull when copying arrays!!**

In [718]:
g = np.array([1, 2, 3])
print(g)

[1 2 3]


In [719]:
h = g
print(h)

[1 2 3]


In [720]:
# As you can see below, when we print "h" again, the change for "g" is passed on to "h". 
#The copy of original "g" is not mantained. 
# It is important to bare this in mind!! 
g[0] = 100
print(g)
print(h)

[100   2   3]
[100   2   3]


In [721]:
# we can prevent this using a ".copy" function
h = g.copy()
print(h)

[100   2   3]


In [722]:
g[1] = 200
print(g)
print(h)

[100 200   3]
[100   2   3]


**Mathematics**

In [723]:
i = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(i)

[[1 2 3 4]
 [5 6 7 8]]


In [724]:
# element wise addition
i + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [725]:
# element wise multiplication
i*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [726]:
j = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])
i + j

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [727]:
i ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [728]:
# Take the sin of all the values
np.sin(i)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [729]:
np.cos(j)

array([[-0.91113026, -0.14550003,  0.75390225,  0.96017029],
       [ 0.28366219, -0.65364362, -0.9899925 , -0.41614684]])

**Linear Algebra**

In [730]:
k = np.random.rand(2, 2)
l = np.full((2, 2), 2)
print(k)
print(l)

[[0.89389798 0.37263772]
 [0.12011719 0.19899817]]
[[2 2]
 [2 2]]


In [731]:
# Matrix multiplication
np.matmul(k, l)

array([[2.53307141, 2.53307141],
       [0.63823072, 0.63823072]])

In [732]:
# find the determinant of the matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [733]:
# calculating the determinant of a matrix
np.linalg.det(k)

0.1331238648567592

**Statistics**

In [735]:
stats = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [736]:
np.min(stats)

1

In [737]:
np.max(stats)

8

In [738]:
# min values comparing rows: output is the number of columns
# think of axis as a vector / direction. axis one goes from left to right
np.min(stats, axis = 1)

array([1, 5])

In [739]:
# min values comparing columns: output is the number of rows
# think of axis as a vector / direction. axis "zero" goes from top to bottom
np.min(stats, axis = 0)

array([1, 2, 3, 4])

In [740]:
# summ all values within a matrix
np.sum(stats)

36

In [741]:
# summ all values within a column: output is number of rows
np.sum(stats, axis = 0)

array([ 6,  8, 10, 12])

In [742]:
# summ all values within a row: output is number of columns
np.sum(stats, axis = 1)

array([10, 26])

**Reorganizing arrays**

In [744]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [745]:
before.shape

(2, 4)

In [750]:
# change the original shape of an array by using the "reshape" function and 
#stating a desired shape (hast to match the number of elements of the original matrix / array)

after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [751]:
# Vertically stacking vextors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [752]:
# it can be dome multiple times
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [755]:
# Horizontal stacks
h1 = np.array([[1, 2, 3, 4], [2, 3, 2, 3]])
h2 = np.array([[5, 6, 7, 8], [8, 7, 8, 7]])

np.hstack([h1, h2])


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [2, 3, 2, 3, 8, 7, 8, 7]])

**Miscellaneous**

Load data

In [761]:
filedata = np.genfromtxt("DataExample.txt", delimiter=",")
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


**Boolean Masking and Advanced Indexing**


In [766]:
# compare the data of all specific entries to a specific size and return true or false
filedata > 10 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [771]:
filedata[filedata > 9]

array([10., 10., 10., 10., 10., 10.])

In [772]:
# You can index with a list in NumPy
i1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
i1[[1,2,8]]

array([2, 3, 9])

In [781]:
# what columns have values > 9
np.any(filedata > 9, axis = 0)

array([False, False, False, False, False, False, False, False, False,
        True])

In [780]:
# only true if all values in a column are greater than "9"
np.all(filedata > 9, axis=0)

array([False, False, False, False, False, False, False, False, False,
        True])

In [782]:
# find those values between two integers 
((filedata > 3) & (filedata < 8))

array([[False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False]])

In [783]:
# find those values "NOT" between two integers 
(~((filedata > 3) & (filedata < 8)))

array([[ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True]])